LunchProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('menu_proposal.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('my_page/', views.UserMyPage.as_view(), name='my_page'),
    path('delete/', views.UserDeleteView.as_view(), name='delete'),
    path('my_page/password_modify/', views.PasswordModifyView.as_view(), name='password_modify'),
    path('my_page/password_modify/done/', views.PasswordModifyDoneView.as_view(), name='password_modify_done'),
    path('my_page/modify_user_info/', views.ModifyUserInfoView.as_view(), name='modify_user_info'),
    path('my_page/modify_eatlog/<date>', views.ModifyEatLogView.as_view(), name='modifyeatlog'),
    path('my_page/add_eatlog/', views.AddEatLogView.as_view(), name='addeatlog'),
    path('my_page/delete_eatlog/<date>',
         views.DeleteEatLogView.as_view(), name='deleatlog'),

]

menu_proposal/urls.py
from django.urls import path

from . import views

app_name = 'menu_proposal'

urlpatterns = [
    path('', views.Home.home, name="home"),
    path('add/', views.MenuCreateView.as_view(), name="add"),
    path('edit/', views.MenuEditView.as_view(), name="edit"),
    path('edit/', views.MenuEditView.as_view(), name="edit_page"),
    path('list/', views.MenuListView.as_view(), name="list"),
    path('list/', views.MenuListView.as_view(), name="list_page"),
    path('list/<pk>', views.MenuDetailView.as_view(), name="detail"),
    path('update/<pk>', views.MenuUpdateView.as_view(), name="update"),
    path('delete/<pk>', views.MenuDeleteView.as_view(), name="delete"),
    path('proposal/', views.MenuProposalView.as_view(), name='proposal'),
]

menu_proposal/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
import os


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    name = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('images', name)
# Create your models here.


class Allergies(models.Model):

    allergy_name = models.TextField(("アレルギー（Allergic substance）"))

    class Meta:
        verbose_name = ("allergies")
        verbose_name_plural = ("allergies")

    def __str__(self):
        return self.allergy_name


class Genres(models.Model):
    genre_name = models.TextField(("ジャンル名（Genre）"))

    class Meta:
        verbose_name = ("Genres")
        verbose_name_plural = ("Genres")

    def __str__(self):
        return self.genre_name


class Menu(models.Model):

    menu_name = models.CharField(
        ("名前（Menu name）"), max_length=128, help_text="※必須", unique=True)
    menu_value = models.IntegerField(
        ("価格（Price (incl. tax)）"), help_text="※必須・0以上の整数", validators=[MinValueValidator(0)])
    menu_energy = models.FloatField(
        ("カロリー（Energy）"), help_text="※必須・0以上の整数", validators=[MinValueValidator(0.0)])
    menu_carbohydrate = models.FloatField(
        ("炭水化物（Carbohydrates）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_salt_content = models.FloatField(
        ("塩分（Salt）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_lipid = models.FloatField(
        ("脂質（Fat）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_protein = models.FloatField(
        ("タンパク質（Protein）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_red_point = models.FloatField(
        ("赤（Red）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_green_point = models.FloatField(
        ("緑（Green）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_yellow_point = models.FloatField(
        ("黄（Yellow）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_picture = models.ImageField(
        ("画像（Image）"), help_text="※任意", upload_to=get_file_path, height_field=None, width_field=None, max_length=None, null=True, blank=True)
    menu_genre = models.ManyToManyField(
        Genres, help_text="※1つ以上選択", verbose_name=("ジャンル（Genre）"))
    menu_allergies = models.ManyToManyField(
        Allergies, verbose_name=("アレルギー（Allergic substance）"), help_text="※任意", null=True, blank=True)

    class Meta:
        verbose_name = ("menu")
        verbose_name_plural = ("menus")

    def __str__(self):
        return self.menu_name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model

from menu_proposal.models import Allergies, Genres

User = get_user_model()


class UserCreateForm(UserCreationForm):
    """ユーザを作成するときのフォーム"""
    allergy = forms.ModelMultipleChoiceField(label="アレルギー", queryset=Allergies.objects.all(),
                                             widget=forms.CheckboxSelectMultiple, required=False)
    genre = forms.ModelMultipleChoiceField(label="好み", queryset=Genres.objects.all(),
                                           widget=forms.CheckboxSelectMultiple)

    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'allergy', 'genre')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

    def save(self, commit=True):
        user = super().save(commit=False)

        if commit:
            user.save()
            self.save_m2m()
        return user


class PasswordModifyForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ModifyUserInfoForm(forms.ModelForm):
    email = forms.CharField(label='email', required=True)
    allergy = forms.ModelMultipleChoiceField(label="アレルギー", queryset=Allergies.objects.all(),
                                             widget=forms.CheckboxSelectMultiple, required=False)
    genre = forms.ModelMultipleChoiceField(label="好み", queryset=Genres.objects.all(),
                                           widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = User
        fields = ['email', 'allergy', 'genre']

accounts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import logout
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

import plotly
import datetime
from collections import OrderedDict

from accounts.models import User, EatLog
from .forms import UserCreateForm, PasswordModifyForm, ModifyUserInfoForm
from menu_proposal.models import Menu
import collections
from django.contrib import messages

class OnlyYouMixin(UserPassesTestMixin):
    """
    異なるユーザからのアクセスを防ぐアクセス制限
    """
    raise_exception = False

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class SignUpView(generic.CreateView):
    """ユーザ登録ページのView"""
    form_class = UserCreateForm
    success_url = reverse_lazy('accounts:signup_successful')
    template_name = 'accounts/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'accounts/signup_successful.html')

        context = {
            'form': form,
        }

        return render(request, 'accounts/signup.html', context)


class UserMyPage(LoginRequiredMixin, generic.TemplateView):
    """マイページのView"""
    template_name = 'accounts/user_my_page.html'

    class Data:
        __slots__ = ['tax_rate', 'menu', 'price', 'energy', 'carbohydrates', 'salt', 'fat', 'protein', 'red', 'green', 'yellow']

        def __init__(self, menu=None):

            if menu is not None:
                self.menu = [menu.menu_name]
                self.price = menu.menu_value
                self.energy = menu.menu_energy
                self.carbohydrates = menu.menu_carbohydrate
                self.salt = menu.menu_salt_content
                self.fat = menu.menu_lipid
                self.protein = menu.menu_protein
                self.red = menu.menu_red_point
                self.green = menu.menu_green_point
                self.yellow = menu.menu_yellow_point
            else:
                self.menu = list()
                self.price = self.energy = self.carbohydrates = self.salt = self.fat = self.protein = self.red = self.green = self.yellow = 0

        def __add__(self, other):
            self.menu += other.menu
            self.menu.sort()
            self.price += other.price
            self.energy += other.energy
            self.carbohydrates += other.carbohydrates
            self.salt += other.salt
            self.fat += other.fat
            self.protein += other.protein
            self.red += other.red
            self.green += other.green
            self.yellow += other.yellow

            return self

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['user'] = User.objects.get(id=self.request.user.id)

        eat_log = EatLog.objects.filter(user=self.request.user).order_by('eat_datetime')
        nutrient_shift = OrderedDict()
        date_time = list()

        for log in eat_log:
            if log.eat_datetime.isoformat() not in nutrient_shift.keys():
                date_time.append(log.eat_datetime)
                nutrient_shift[log.eat_datetime.isoformat()] = self.Data()

            for m in log.menu.all():
                nutrient_shift[log.eat_datetime.isoformat()] += self.Data(m)

        context['nutrient_shift'] = nutrient_shift

        date = list()
        _3m_ago = datetime.date.today() - datetime.timedelta(days=6)
        for d in range(7):
            date.append(_3m_ago + datetime.timedelta(days=d))

        data = list()
        nut = {
            'price': [],
            'energy': [],
            'carbohydrates': [],
            'salt': [],
            'fat': [],
            'protein': [],
            'red': [],
            'green': [],
            'yellow': []
        }
        for d in date:
            if d.isoformat() in nutrient_shift.keys():
                key = d.isoformat()
                nut['price'].append(nutrient_shift[key].price)
                nut['energy'].append(nutrient_shift[key].energy)
                nut['carbohydrates'].append(nutrient_shift[key].carbohydrates)
                nut['salt'].append(nutrient_shift[key].salt)
                nut['fat'].append(nutrient_shift[key].fat)
                nut['protein'].append(nutrient_shift[key].protein)
                nut['red'].append(nutrient_shift[key].red)
                nut['green'].append(nutrient_shift[key].green)
                nut['yellow'].append(nutrient_shift[key].yellow)

            else:
                nut['price'].append(0)
                nut['energy'].append(0)
                nut['carbohydrates'].append(0)
                nut['salt'].append(0)
                nut['fat'].append(0)
                nut['protein'].append(0)
                nut['red'].append(0)
                nut['green'].append(0)
                nut['yellow'].append(0)

        for g in nut.keys():
            data.append(plotly.graph_objs.Scatter(x=date, y=nut[g], name=g))

        layout = plotly.graph_objs.Layout(
            xaxis={"title": "日付"},
            yaxis={"title": "栄養素", "rangemode":"tozero"},
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)',
            font=dict(color='rgba(255,255,255,1)')
        )
        figure = plotly.graph_objs.Figure(data=data, layout=layout)
        div = plotly.offline.plot(figure, auto_open=False, output_type='div')
        context['graph'] = div

        return context


class UserDeleteView(generic.TemplateView):
    """削除のView"""
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            User.objects.filter(email=self.request.user.email).delete()
            logout(self.request)
            return render(self.request, 'accounts/user_delete.html')
        else:
            return redirect('menu_proposal:home')


class PasswordModifyView(PasswordChangeView):
    form_class = PasswordModifyForm
    success_url = reverse_lazy('accounts:password_modify_done')
    template_name = 'accounts/modify_password.html'


class PasswordModifyDoneView(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'accounts/password_modify_done.html'


class ModifyUserInfoView(LoginRequiredMixin, generic.FormView):
    form_class = ModifyUserInfoForm
    template_name = 'accounts/modify_user_info.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=request.user)

        if form.is_valid():
            form.save()

            return redirect('accounts:my_page')

        context = {
            'form': form
        }

        return render(request, 'accounts/modify_user_info.html', context)

    def get_initial(self):
        initial = super().get_initial()
        user = self.request.user

        initial['email'] = user.email

        # 好みのジャンルの初期値の設定
        genre = []
        for g in user.genre.all():
            genre.append(g.pk)
        initial['genre'] = genre
        # アレルギーの初期値の設定
        allergy = []
        for a in user.allergy.all():
            allergy.append(a.pk)
        initial['allergy'] = allergy

        return initial


class ModifyEatLogView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'accounts/modify_eatlog.html'

    def post(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_list'] = Menu.objects.all()
        #現在の献立のリストを受け取る
        if request.POST.getlist('eat_log', None):
            context['eatlog_list'] = self.request.POST.getlist('eat_log', None)

        #追加を押されたとき、そのメニューを追加
        if request.POST.get('add', None):
            add = request.POST.get('add', None)
            if 'eatlog_list' in context.keys():
                context['eatlog_list'].append(add)
            else:
                context['eatlog_list'] = [add]

            eatlog = [int(i) for i in context['eatlog_list']]
            eatlog.sort()
            context['eatlog_list']=eatlog

        #削除を押されたとき、そのメニューを削除
        if request.POST.get('del', None):
            delete = request.POST.get('del', None)
            context['eatlog_list'].remove(delete)

        #決定を押されたとき、食事履歴を更新
        if request.POST.get('update', None):
            if 'eatlog_list' in context.keys():
                eatlog = [int(i) for i in context['eatlog_list']]
            else:
                messages.error(self.request, 'メニューを一つ以上指定してください')
                return render(request, 'accounts/modify_eatlog.html', context)
            log_list = EatLog.objects.filter(
                user=self.request.user, eat_datetime=self.kwargs.get('date'))
            log_list=[i for i in log_list]

            eatlog_tuple = collections.Counter(eatlog)
            eatlog_tuple = eatlog_tuple.most_common()

            for i in range(eatlog_tuple[0][1]):
                dup = [x for x in set(eatlog) if eatlog.count(x) > i]
                if len(log_list) > i:
                    log_list[i].menu.set(dup)
                else:
                    log_list.append(EatLog.objects.create(
                        user=self.request.user, eat_datetime=self.kwargs.get('date')))
                    log_list[i].menu.set

            for log in range(eatlog_tuple[0][1], len(log_list)):
                log_list[log].delete()

            del log_list[eatlog_tuple[0][1]:]

            for log in log_list:
                log.save()
            messages.success(self.request, str(
                self.kwargs.get('date')) + 'の献立を修正しました')
            return redirect('accounts:my_page')

        return render(request, 'accounts/modify_eatlog.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

accounts/templates/accounts/add_eatlog.html
{% extends 'base.html' %}
{% load index%}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <h2>食事履歴の登録</h2>
    <h3>登録する日付</h3>
    <input type="date" name="add_date" value={{date}}>
    <h3>現在の献立</h3>
    <div>
        <table width="100%" id="menu_list_view">
            {% for i in eatlog_list %}
            <tr>
                <th width="80%" align="left">
                    {{i|get_menuname:i}}
                    <input type="hidden" name="eat_log" value={{i}}>
                </th>
                <th width="20%">
                    <button class="btn-shine" name="del" value={{i}}>削除</button>
                </th>
            </tr>
            {% endfor %}
        </table>
        <div align="center">
        <button class="btn-shine submit" name="update" value="update">決定</button>
        </div>
    </div>
    <h3>メニューリスト</h3>
    <div>
        {% for menu in menu_list %}
        <div>
            <table width="100%">
                <tr>
                    <th width="80%" align="left">
                        {{menu.menu_name}}
                    </th>
                    <th width="20%">
                        <button class="btn-shine" name="add" value={{menu.id}}>追加</button>
                    </th>
                </tr>
            </table>
        </div>
        {% endfor %}

    </div>
</form>
<a href="{% url 'accounts:my_page' %}">プロフィールに戻る</a>
{% endblock %}

accounts/templates/accounts/del_eatlog.html
{% extends 'base.html' %}
{% load index %}
{% block content %}
<h2>食事履歴の削除</h2>
<div class="container">
    <div class="row">
        <div class="col-12">
            <p>{{ date }}の献立を削除していいですか?</p>
            <form method="post">
                <button class="btn-shine danger" name="delete" value={{date}}>削除する</button>
            <a class="btn-shine" href=" {% url 'accounts:my_page' %}">戻る</a>
                {% csrf_token %}
            </form>
        </div>
        <div>
            <h3>{{date}}の献立</h3>
            {% for i in eatlog_list %}
                {{i|get_menuname:i}}
                <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/modify_eatlog.html
{% extends 'base.html' %}
{% load index%}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <h2>食事履歴の修正</h2>
    <h3>現在の献立</h3>
        <div>
            <table width="100%" id="menu_list_view">
                {% for i in eatlog_list %}
                <tr>
                    <th width="80%" align="left">
                        {{i|get_menuname:i}}
                        <input type="hidden" name="eat_log" value={{i}}>
                    </th>
                    <th width="20%">
                        <button class="btn-shine" name="del" value={{i}}>削除</button>
                    </th>
                </tr>
            {% endfor %}
            </table>
            <div align="center">
            <button class="btn-shine submit" name="update" value="update">決定</button>
            </div>
        </div>
    <h3>メニューリスト</h3>
        <div>
            {% for menu in menu_list %}
            <div>
                <table width="100%">
                    <tr>
                        <th width="80%" align="left">
                            {{menu.menu_name}}
                        </th>
                        <th width="20%">
                            <button class="btn-shine" name="add" value={{menu.id}}>追加</button>
                        </th>
                    </tr>
                </table>
            </div>
            {% endfor %}

        </div>
</form>
<a href="{% url 'accounts:my_page' %}">プロフィールに戻る</a>
{% endblock %}

accounts/templates/accounts/modify_password.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn-shine">送信</button>
</form>
{% endblock %}

accounts/templates/accounts/modify_user_info.html
{% extends 'base.html' %}

{% block content %}
    <h3>ユーザー情報の変更</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-shine" type="submit">確認</button>
    </form>

    <a href="{% url 'accounts:my_page' %}">プロフィールに戻る</a>
{% endblock %}

accounts/templates/accounts/password_modify_done.html
{% extends 'base.html' %}

{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:my_page' %}">会員情報画面へ</a>
</p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn-shine" type="submit" class="submit">Sign up</button>
    </form>
    </section>
{% endblock %}

accounts/templates/accounts/signup_successful.html
{% extends 'base.html' %}

{% block content %}
    <h1>Signup Successful.</h1>
    <a href="{% url 'login' %}">ログイン画面へ</a>
{% endblock %}

accounts/templates/accounts/user_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>退会が完了しました</h1>
    <P>ご利用ありがとうございました。</P>

    <a href="{% url 'menu_proposal:home' %}">トップに戻る.</a>
{% endblock %}

accounts/templates/accounts/user_my_page.html
{% extends 'base.html' %}

{% block content %}
    <h2>会員情報</h2>
    {% if user.is_superuser %}
        <h3>
            メニューの管理
        </h3>
        <ul class="super">
            <li><a href={% url 'menu_proposal:edit' %} class="act">メニューの削除修正 <span>MENU</span></a></li>
            <li><a href={% url 'menu_proposal:add' %} class="act">メニューの追加<span>MenuAdd</span></a></li>
        </ul>
    {% endif %}

    {% if not user.is_superuser %}
        <h3>
            <a href={% url 'accounts:addeatlog' %}>食事履歴登録</a>
        </h3>

        <h3>食事履歴</h3>
        <dl id="acMenu">
            {% for date, nutrient in nutrient_shift.items %}
                <dt><span class="date">{{ date }}</span></dt>
                <div>
                    <a href={% url 'accounts:modifyeatlog' date %}>修正</a>
                    <a href={% url 'accounts:deleatlog' date %}>削除</a>
                </div>
                <dd>
                    <fieldset>
                        <div>
                            <ul>
                                {% for name in nutrient.menu %}
                                    <li>{{ name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <hr>
                        <div>
                            <table>
                                <tr>
                                    <td>値段(税込み)</td>
                                    <td>{{ nutrient.price|floatformat:0 }} 円</td>
                                </tr>
                                <tr>
                                    <td>カロリー</td>
                                    <td>{{ nutrient.energy|floatformat }} kcal</td>
                                </tr>
                                <tr>
                                    <td>炭水化物</td>
                                    <td>{{ nutrient.carbohydrates|floatformat }} g</td>
                                </tr>
                                <tr>
                                    <td>塩分</td>
                                    <td>{{ nutrient.salt|floatformat }} g</td>
                                </tr>
                                <tr>
                                    <td>脂質</td>
                                    <td>{{ nutrient.fat|floatformat }} g</td>
                                </tr>
                                <tr>
                                    <td>タンパク質</td>
                                    <td>{{ nutrient.protein|floatformat }} g</td>
                                </tr>
                                <tr>
                                    <td>赤</td>
                                    <td>{{ nutrient.red|floatformat }}</td>
                                </tr>
                                <tr>
                                    <td>緑</td>
                                    <td>{{ nutrient.green|floatformat }}</td>
                                </tr>
                                <tr>
                                    <td>黄</td>
                                    <td>{{ nutrient.yellow|floatformat }}</td>
                                </tr>
                            </table>
                        </div>
                    </fieldset>
                </dd>
            {% endfor %}
        </dl>
        <script>
            $("#acMenu dt").on("click", function () {
                $(this).next().next().slideToggle();
            });
        </script>
        <style>
        dl dd {
            display: none;
        }

        .date:hover {
            cursor: pointer;
            text-decoration: underline;
            color: #FFFFFF;
        }
        </style>

    <section>
    <h3>栄養推移</h3>
    {% if graph %}
        {{ graph|safe }}
    {% endif %}
    </section>

    {% endif %}


    <section>
        <h3>ユーザ情報　<a href="{% url 'accounts:modify_user_info' %}">編集</a></h3>
        <table border="3">
            <tr>
                <td>メールアドレス</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>アレルギー</td>
                <td>
                    {% for allelgy in user.allergy.all %}
                        {{ allelgy.allergy_name }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>好みのジャンル</td>
                <td>
                    {% for genre in user.genre.all %}
                        {{ genre.genre_name }}
                    {% endfor %}
                </td>
            </tr>
        </table>
    </section>

    <a href="{% url 'accounts:password_modify' %}">パスワード変更</a> <br>
    {% if not user.is_superuser %}
        <button id="delete_user" class="btn-shine danger" type="button">アカウント削除</button>
        <script>
            let btn = document.getElementById('delete_user');

            btn.addEventListener('click', function () {
                let ret = window.confirm('本当に削除しますか？');

                if (ret) {
                    window.location.href = '{% url 'accounts:delete' %}'
                }
            })
        </script>
    {% endif %}

{% endblock %}