LunchProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('menu_proposal.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('my_page/', views.UserMyPage.as_view(), name='my_page'),
    path('delete/', views.UserDeleteView.as_view(), name='delete'),
    path('my_page/password_modify/', views.PasswordModifyView.as_view(), name='password_modify'),
    path('my_page/password_modify/done/', views.PasswordModifyDoneView.as_view(), name='password_modify_done'),
    path('my_page/modify_user_info/', views.ModifyUserInfoView.as_view(), name='modify_user_info'),
    path('my_page/modify_eatlog/<date>', views.ModifyEatLogView.as_view(), name='modifyeatlog'),
    path('my_page/add_eatlog/', views.AddEatLogView.as_view(), name='addeatlog'),
    path('my_page/delete_eatlog/<date>',
         views.DeleteEatLogView.as_view(), name='deleatlog'),

]

menu_proposal/urls.py
from django.urls import path

from . import views

app_name = 'menu_proposal'

urlpatterns = [
    path('', views.Home.home, name="home"),
    path('add/', views.MenuCreateView.as_view(), name="add"),
    path('edit/', views.MenuEditView.as_view(), name="edit"),
    path('edit/', views.MenuEditView.as_view(), name="edit_page"),
    path('list/', views.MenuListView.as_view(), name="list"),
    path('list/', views.MenuListView.as_view(), name="list_page"),
    path('list/<pk>', views.MenuDetailView.as_view(), name="detail"),
    path('update/<pk>', views.MenuUpdateView.as_view(), name="update"),
    path('delete/<pk>', views.MenuDeleteView.as_view(), name="delete"),
    path('proposal/', views.MenuProposalView.as_view(), name='proposal'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>食事提案Webアプリ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ここにサイト説明を入れます">
    <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <script type="text/javascript" src="{% static 'script/openclose.js' %}"></script>
    <script type="text/javascript" src="{% static 'script/fixmenu_pagetop.js' %}"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.2.3.min.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>


<body>

    <header>
        <div class="inner">
            <h1 id="logo"><a href="/"><img src="{% static 'img/logo.png' %}"></a></h1>
            <div id="contact">
            </div>
        </div>
    </header>

    <!--PC用（801px以上端末）メニュー-->
    <nav id="menubar">
        <ul class="inner">
            <li><a href="/">ホーム<span>HOME</span></a></li>
            {% if user.is_superuser %}
            <li><a href={% url 'menu_proposal:edit' %} class="act">メニュー修正・削除 <span>MENUEDIT</span></a></li>
            <li><a href={% url 'menu_proposal:add' %} class="act">メニューの追加<span>MENUADD</span></a></li>
            {% else %}
            <li><a href={% url 'menu_proposal:list' %} class="act">メニュー<span>SERVICE</span></a></li>
            <li><a href={% url 'menu_proposal:proposal' %} class="act">献立提案<span>PROPOSAL</span></a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}" class="logout">ログアウト<span>Logout</span></a></li>
            <li><a href="{% url 'accounts:my_page' %}" class="info">会員情報<span>User Menu</span></a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="signup">会員登録<span>SIGNUP</span></a></li>
            <li><a href="{% url 'login' %}" class="login">ログイン<span>LOGIN</span></a></li>
            {% endif %}
        </ul>
    </nav>
    <!--小さな端末用（800px以下端末）メニュー-->
    <nav id="menubar-s">
        <ul>
            <li><a href="/">ホーム<span>HOME</span></a></li>
            {% if user.is_superuser %}
            <li><a href={% url 'menu_proposal:edit' %} class="act">メニューの削除修正 <span>MENUEDIT</span></a></li>
            <li><a href={% url 'menu_proposal:add' %} class="act">メニューの追加<span>MENUADD</span></a></li>
            {% else %}
            <li><a href={% url 'menu_proposal:list' %} class="act">メニュー<span>SERVICE</span></a></li>
            <li><a href={% url 'menu_proposal:proposal' %} class="act">献立提案<span>PROPOSAL</span></a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}" class="logout">ログアウト<span>Logout</span></a></li>
            <li><a href="{% url 'accounts:my_page' %}" class="info">会員情報<span>User Menu</span></a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="signup">会員登録<span>Signup</span></a></li>
            <li><a href="{% url 'login' %}" class="login">ログイン<span>LOGIN</span></a></li>
            {% endif %}
        </ul>
    </nav>

    <div id="contents" class="inner">
        <div id="contents-in">
            <div id="main">

                <section>
                    <div class="content">
                        {% if messages %}
                        <div>
                            {% for message in messages %}
                            <p> {{ message }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% block content %}
                        {% endblock %}
                    </div>
                </section>
            </div>
            <!--/#main-->


            <div id="side">
            </div>
            <!--/#side-->
        </div>
        <!--/#contents-in-->
    </div>
    <!--/#contents-->

    <footer>
        <!--/footermenu-->

        <div id="copyright">
            <small>Copyright&copy; <a href="index.html">SAMPLE COMPANY</a> All Rights Reserved.</small>
            <span class="pr"><a href="http://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
        </div>

    </footer>

    <p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

    <!--小さな端末用（800px以下端末）メニュー-->
    <script type="text/javascript">
        if (OCwindowWidth() <= 800) {
            open_close("newinfo_hdr", "newinfo");
        }
    </script>

    <!--メニュー開閉ボタン-->
    <div id="menubar_hdr" class="close"></div>
    <!--メニューの開閉処理条件設定　800px以下-->
    <script type="text/javascript">
        if (OCwindowWidth() <= 800) {
            open_close("menubar_hdr", "menubar-s");
        }
    </script>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load index %}

{% block content %}
    <section id="about">

    <h2>昼食提案アプリケーション</h2>

    <h3>About</h3>
    <p>
        昼食提案です<br>
        ここに何か書く
    </p>

</section>
{% endblock %}