LunchProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('menu_proposal.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('my_page/', views.UserMyPage.as_view(), name='my_page'),
    path('delete/', views.UserDeleteView.as_view(), name='delete'),
    path('my_page/password_modify/', views.PasswordModifyView.as_view(), name='password_modify'),
    path('my_page/password_modify/done/', views.PasswordModifyDoneView.as_view(), name='password_modify_done'),
    path('my_page/modify_user_info/', views.ModifyUserInfoView.as_view(), name='modify_user_info'),
    path('my_page/modify_eatlog/<date>', views.ModifyEatLogView.as_view(), name='modifyeatlog'),
    path('my_page/add_eatlog/', views.AddEatLogView.as_view(), name='addeatlog'),
    path('my_page/delete_eatlog/<date>',
         views.DeleteEatLogView.as_view(), name='deleatlog'),

]

menu_proposal/urls.py
from django.urls import path

from . import views

app_name = 'menu_proposal'

urlpatterns = [
    path('', views.Home.home, name="home"),
    path('add/', views.MenuCreateView.as_view(), name="add"),
    path('edit/', views.MenuEditView.as_view(), name="edit"),
    path('edit/', views.MenuEditView.as_view(), name="edit_page"),
    path('list/', views.MenuListView.as_view(), name="list"),
    path('list/', views.MenuListView.as_view(), name="list_page"),
    path('list/<pk>', views.MenuDetailView.as_view(), name="detail"),
    path('update/<pk>', views.MenuUpdateView.as_view(), name="update"),
    path('delete/<pk>', views.MenuDeleteView.as_view(), name="delete"),
    path('proposal/', views.MenuProposalView.as_view(), name='proposal'),
]

menu_proposal/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
import os


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    name = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('images', name)
# Create your models here.


class Allergies(models.Model):

    allergy_name = models.TextField(("アレルギー（Allergic substance）"))

    class Meta:
        verbose_name = ("allergies")
        verbose_name_plural = ("allergies")

    def __str__(self):
        return self.allergy_name


class Genres(models.Model):
    genre_name = models.TextField(("ジャンル名（Genre）"))

    class Meta:
        verbose_name = ("Genres")
        verbose_name_plural = ("Genres")

    def __str__(self):
        return self.genre_name


class Menu(models.Model):

    menu_name = models.CharField(
        ("名前（Menu name）"), max_length=128, help_text="※必須", unique=True)
    menu_value = models.IntegerField(
        ("価格（Price (incl. tax)）"), help_text="※必須・0以上の整数", validators=[MinValueValidator(0)])
    menu_energy = models.FloatField(
        ("カロリー（Energy）"), help_text="※必須・0以上の整数", validators=[MinValueValidator(0.0)])
    menu_carbohydrate = models.FloatField(
        ("炭水化物（Carbohydrates）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_salt_content = models.FloatField(
        ("塩分（Salt）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_lipid = models.FloatField(
        ("脂質（Fat）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_protein = models.FloatField(
        ("タンパク質（Protein）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_red_point = models.FloatField(
        ("赤（Red）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_green_point = models.FloatField(
        ("緑（Green）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_yellow_point = models.FloatField(
        ("黄（Yellow）"), help_text="※必須・0以上の小数", validators=[MinValueValidator(0.0)])
    menu_picture = models.ImageField(
        ("画像（Image）"), help_text="※任意", upload_to=get_file_path, height_field=None, width_field=None, max_length=None, null=True, blank=True)
    menu_genre = models.ManyToManyField(
        Genres, help_text="※1つ以上選択", verbose_name=("ジャンル（Genre）"))
    menu_allergies = models.ManyToManyField(
        Allergies, verbose_name=("アレルギー（Allergic substance）"), help_text="※任意", null=True, blank=True)

    class Meta:
        verbose_name = ("menu")
        verbose_name_plural = ("menus")

    def __str__(self):
        return self.menu_name

templates/Menu/create.html
{% extends 'base.html' %}

{% block content %}
<h2>メニュー登録</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label>{{field.label}}</label>
    {% if field.help_text %}
    <span>{{ field.help_text }}</span>
    {% endif %}
    <br>
    {% if field.errors %}
    <div>
        {% for error in field.errors %}
        {{ error }}<br>
        {% endfor %}
    </div>
    {% endif %}

    {% for i in field %}
    <label class="selectbox">
        {{i}}
    </label>
    {% endfor %}
    <br>
    {% endfor %}
    <div align="center">
    <input class="btn-shine submit" type="submit" value="追加">
    </div>
</form>
{% endblock content %}

templates/Menu/delete.html
{% extends 'base.html' %}
{% block content %}
<h2>メニュー削除</h2>
<div class="container">
    <div class="row">
        <div class="col-12">
            <p>{{ object }} を削除していいですか?</p>
            <form method="post">
                <button class="btn-shine danger">削除する</button>
                {% csrf_token %}
            </form>
            <br>
            <a class="btn-shine" href="{% url 'menu_proposal:edit' %}">戻る</a>
        </div>
    </div>
</div>
{% endblock %}

templates/Menu/detail.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_superuser %}
<a href={% url 'menu_proposal:edit' %}>一覧に戻る</a>
{% else %}
<a href={% url 'menu_proposal:list' %}>一覧に戻る</a>
{% endif %}

<h3>{{menu.menu_name}}</h3>
{% if user.is_superuser %}
<a href={% url 'menu_proposal:update' pk=menu.pk %}>メニューの修正</a>
{% endif %}
{% if menu.menu_picture %}
<th>画像：<br><img src="{{ menu.menu_picture.url }}" width="50%" height="50%" /></th>
{% endif %}
<table border="1" width="500" cellspacing="0" cellpadding="5" bordercolor="#FFFFFF">
    <tr>
        <th>
            価格
        </th>
        <th>
            {{menu.menu_value}}円
        </th>
    </tr>
    <tr>
        <th>
            3群点数
        </th>
        <th>
            赤：{{menu.menu_red_point}}
            <br>
            緑：{{menu.menu_green_point}}
            <br>
            黄：{{menu.menu_yellow_point}}
        </th>
    </tr>
    <tr>
        <th>
            カロリー
        </th>
        <th>
            {{menu.menu_energy}}kcal
        </th>
    </tr>
    <tr>
        <th>
            脂質
        </th>
        <th>
            {{menu.menu_lipid}}g
        </th>
    </tr>
    <tr>
        <th>
            塩分
        </th>
        <th>
            {{menu.menu_salt_content}}g
        </th>
    </tr>
    <tr>
        <th>
            炭水化物
        </th>
        <th>
            {{menu.menu_carbohydrate}}g
        </th>
    </tr>
    <tr>
        <th>
            タンパク質
        </th>
        <th>
            {{menu.menu_protein}}g
        </th>
    </tr>
    <tr>
        <th>
            ジャンル
        </th>
        <th>

            {% for genre in menu.menu_genre.all %}
            {{genre.genre_name}}
            <br>
            {% endfor %}
        </th>
    </tr>
    <tr>

        <th>
            アレルギー
        </th>
        <th>
            {% for Allergies in menu.menu_allergies.all %}
            {{Allergies.allergy_name}}
            {% endfor %}
        </th>
    </tr>
</table>
<details open>
    <summary>栄養素のグラフ</summary>
    {{graph|safe}}
</details>
{% endblock content %}

templates/Menu/list.html
{% extends 'base.html' %}

{% block content %}
<h2>メニューリスト</h2>
<h3>検索条件</h3>
<form method="post">
    {% csrf_token %}
    {% for field in test_form %}
    <label>{{field.label}}:</label>
    <br>
    {% for i in field %}
    <label class="selectbox">
        {{i}}
    </label>
    {% endfor %}
    <br>
    {% endfor %}

    <div>
        <label>ソート条件</label> <br>
        <input type="radio" name="order" value="order_name" checked><label>名前</label> <br>
        <input type="radio" name="order_by_name" value="ascend" checked> 昇順
        <input type="radio" name="order_by_name" value="descend"> 降順

        <br><br>

        <input type="radio" name="order" value="order_price"><label>値段</label> <br>
        <input type="radio" name="order_by_price" value="ascend" checked> 昇順
        <input type="radio" name="order_by_price" value="descend"> 降順
    </div>
    <input class="btn-shine" type="submit" id="button" name="button" value="検索">
</form>
<br>
<h3>検索結果</h3>
{% if menu_list %}
<table border="3">
    <tr>
        <th width="80%">メニュー名</th>
        <th width="20%">税込み価格</th>
    </tr>
    {% for menu in menu_list %}
    <tr>
        <td align="left" width="80%">
            <a href={% url 'menu_proposal:detail' pk=menu.id %}>{{menu.menu_name}}</a>
        </td>
        <td align="right" width="20%">
            {{menu.menu_value}}円
        </td>
    </tr>
    {% endfor %}
</table>
<!--ページ送り-->
{% if page_obj.has_previous %}
<a align="left" href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<span>{{ num }}</span>
{% else %}
<a href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}
{% else %}
<div>検索結果がありません</div>
{% endif %}
{% endblock content %}

templates/Menu/superuserlist.html
{% extends 'base.html' %}

{% block content %}
<h2>メニューの修正削除</h2>
<h3>検索条件</h3>
<form method="post">
    {% csrf_token %}
    {% for field in test_form %}
    <label>{{field.label}}:</label>
    <br>
    {% for i in field %}
    <label class="selectbox">
        {{i}}
    </label>
    {% endfor %}
    <br>
    {% endfor %}
    <input class="btn-shine" type="submit" id="button" name="button" value="検索">
</form>
<br>
<h3>検索結果</h3>
{% if menu_list %}
<table width="100%" border="3">
    <tr>
        <th width="70%">メニュー名</th>
        <th width="16%">税込み価格</th>
        <th></th>
        <th></th>
    </tr>

    {% for menu in menu_list %}
    <tr>
        <td width="70%" align="left">
            <a href={% url 'menu_proposal:detail' pk=menu.id %}>{{menu.menu_name}}</a>
        </td>
        <td width="16%" align="right">
            {{menu.menu_value}}円
        </td>
        <td width="7%" align="center">
            <a href="{% url 'menu_proposal:update' menu.pk %}">修正</a>
        </td>
        <td width="7%" align="center">
            <a href="{% url 'menu_proposal:delete' menu.pk %}">削除</a>
        </td>
    </tr>
    {% endfor %}
</table>

<!--ページ送り-->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<span>{{ num }}</span>
{% else %}
<a href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}
{% else %}
<div>検索結果がありません</div>
{% endif %}
{% endblock content %}

templates/Menu/update.html
{% extends 'base.html' %}

{% block content %}
<h2>メニュー修正</h2>
<a href={% url 'menu_proposal:edit' %}>一覧に戻る</a>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label>{{field.label}}</label>
    {% if field.help_text %}
    <span>{{ field.help_text }}</span>
    {% endif %}
    <br>
    {% if field.errors %}
    <div>
        {% for error in field.errors %}
        {{ error }}<br>
        {% endfor %}
    </div>
    {% endif %}

    {% for i in field %}
    <label class="selectbox">
        {{i}}
    </label>
    {% endfor %}
    <br>
    {% endfor %}
    <div align="center">
    <input class="btn-shine submit" type="submit" value="修正"><br>
    </div>
</form>

{% endblock content %}